// Generated from "RMI Sustainability Self Assessment 2026.xlsx".
// Do not hand-edit: regenerate from the source workbook instead.

export type SectionId = "governance" | "economic" | "environmental" | "social";

export type Question = {
  id: string;
  section: SectionId;
  topic: string;
  question: string;
  followUp: string | null;
  weight: number;
  sdg: string | null;
  gri: string | null;
};

export type Section = {
  id: SectionId;
  title: string;
  short: string;
  blurb: string;
};

export const SECTIONS: Section[] = [
  {
    id: "governance",
    title: "Corporate Governance",
    short: "Governance",
    blurb:
      "How your board, leadership and controls hold the organisation accountable for its sustainability commitments.",
  },
  {
    id: "economic",
    title: "Economic Viability",
    short: "Economic",
    blurb:
      "Whether sustainability is wired into your strategy, capital allocation and the long-term value you create.",
  },
  {
    id: "environmental",
    title: "Environmental Impact",
    short: "Environmental",
    blurb:
      "Your footprint across energy, emissions, water, waste, packaging and the materials you source.",
  },
  {
    id: "social",
    title: "Social Responsibility",
    short: "Social",
    blurb:
      "How you treat people \u2014 employees, suppliers, customers and the communities you operate in.",
  },
];

export const SECTION_ORDER: SectionId[] = [
  "governance",
  "economic",
  "environmental",
  "social",
];

export const CLIENT_QUESTIONS: Question[] = [
  { id: "c-governance-board-oversight", section: "governance", topic: "Board Oversight", question: "Does the board of directors provide oversight on sustainability-related risks and strategies?", followUp: "Does a specific Board committee have formal responsibility for ESG performance?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-9 to 2-18" },
  { id: "c-governance-leadership-accountability", section: "governance", topic: "Leadership & Accountability", question: "Is accountability for sustainability performance clearly assigned to specific leaders within the organization?", followUp: "Is executive compensation tied to the achievement of sustainability targets?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-9 to 2-18" },
  { id: "c-governance-ethical-conduct", section: "governance", topic: "Ethical Conduct", question: "Does your company have policies and training in place to prevent corruption and bribery?", followUp: "Do you have a 24/7 anonymous whistleblowing hotline accessible to all employees?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 205, 206" },
  { id: "c-governance-risk-management-integration", section: "governance", topic: "Risk Management Integration", question: "Are ESG factors integrated into the company\u2019s overall risk management framework?", followUp: "Is a 'Sustainability Risk' category included in your corporate Risk Register?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-23" },
  { id: "c-governance-board-diversity", section: "governance", topic: "Board Diversity", question: "Does the board of directors reflect a diversity of backgrounds and skills, including sustainability expertise?", followUp: "Does your board include members with specific ESG or climate expertise?", weight: 1.3243, sdg: "SDG 5, 16", gri: "GRI 405" },
  { id: "c-governance-stakeholder-engagement", section: "governance", topic: "Stakeholder Engagement", question: "Does your company have a formal process for engaging with stakeholders regarding sustainability concerns?", followUp: "Do you conduct a formal Materiality Assessment with stakeholders at least every 2 years?", weight: 1.3243, sdg: "SDG 17", gri: "GRI 2-29" },
  { id: "c-governance-internal-controls", section: "governance", topic: "Internal Controls", question: "Are there internal controls and audit functions in place to ensure the accuracy of sustainability reporting?", followUp: "Is your sustainability data subject to limited or reasonable external assurance?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2" },
  { id: "c-governance-responsible-lobbying", section: "governance", topic: "Responsible Lobbying", question: "Does your company have a clear policy on political engagement and lobbying that aligns with its values?", followUp: "Do you disclose all memberships in trade associations that influence climate policy?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 415" },
  { id: "c-governance-purpose-values", section: "governance", topic: "Purpose & Values", question: "Are the company's purpose and values integrated into day-to-day operations and decision-making?", followUp: "Is your 'Company Purpose' legally embedded in your articles of association (e.g., B Corp status)?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-23" },
  { id: "c-governance-whistleblower-protection", section: "governance", topic: "Whistleblower Protection", question: "Does your company have a confidential process for reporting unethical behavior without fear of retaliation?", followUp: "Do you have a zero-retaliation policy for whistleblowers that is strictly enforced?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-25, 2-26" },
  { id: "c-governance-indigenous-knowledge-traditional-leadership", section: "governance", topic: "Indigenous Knowledge & Traditional Leadership", question: "Does the company consult with local traditional leaders or utilize indigenous knowledge in environmental impact and land use planning?", followUp: "Is there a formal seat or observer status for community/traditional elders in your sustainability oversight committees?", weight: 3.0, sdg: "SDG 11, 16", gri: "GRI 411" },
  { id: "c-governance-anti-corruption-facilitation-payments", section: "governance", topic: "Anti-Corruption (Facilitation Payments)", question: "Do you have a specific zero-tolerance policy and training program targeting 'facilitation payments' or informal 'grease' fees?", followUp: "Do you have an anonymous reporting mechanism specifically for reporting corruption demands from public officials?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 205" },
  { id: "c-governance-land-rights-fpic", section: "governance", topic: "Land Rights & FPIC", question: "Does the company adhere to the principle of Free, Prior, and Informed Consent (FPIC) for all land-use activities?", followUp: "Do you have a land grievance mechanism accessible to local and ancestral communities?", weight: 1.3243, sdg: "SDG 1, 16", gri: "GRI 411" },
  { id: "c-economic-sustainable-strategy", section: "economic", topic: "Sustainable Strategy", question: "Is sustainability integrated into your company\u2019s core business strategy for long-term value creation?", followUp: "Does the Board of Directors review and sign off on your sustainability strategy at least annually?", weight: 1.3243, sdg: "SDG 8, 9", gri: "GRI 2" },
  { id: "c-economic-financial-transparency", section: "economic", topic: "Financial Transparency", question: "Does your company disclose how sustainability-related risks and opportunities impact its financial performance?", followUp: "Do you provide a financial breakdown of your \"Green Revenue\" or the costs of climate transition?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 201" },
  { id: "c-economic-risk-management", section: "economic", topic: "Risk Management", question: "Does your company identify and manage sustainability-related risks (e.g., climate, regulatory) that could affect the business?", followUp: "Are ESG risks explicitly listed in your company's Principal Risk Register for Board review?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2" },
  { id: "c-economic-ethical-tax-practices", section: "economic", topic: "Ethical Tax Practices", question: "Does your company have a public policy on tax practices and financial transparency?", followUp: "Do you publish a Country-by-Country (CbC) tax report to show your global tax footprint?", weight: 3.0, sdg: "SDG 16, 17", gri: "GRI 207" },
  { id: "c-economic-innovation", section: "economic", topic: "Innovation", question: "Does your company\u2019s innovation strategy focus on developing sustainable products that create new market opportunities?", followUp: "What % of your annual R&D budget is specifically allocated to resource-efficient or \"green\" products?", weight: 3.0, sdg: "SDG 9", gri: "GRI 203" },
  { id: "c-economic-long-term-value", section: "economic", topic: "Long-Term Value", question: "Does your company communicate long-term value for stakeholders beyond just shareholders?", followUp: "Do you perform a formal \"Double Materiality\" assessment to evaluate both financial and societal impacts?", weight: 1.3243, sdg: "SDG 8", gri: "GRI 201" },
  { id: "c-economic-circular-business-models", section: "economic", topic: "Circular Business Models", question: "Has your company explored or adopted circular business models (e.g., take-back programs)?", followUp: "Do you perform a formal \"Double Materiality\" assessment to evaluate both financial and societal impacts?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 306" },
  { id: "c-economic-capital-allocation", section: "economic", topic: "Capital Allocation", question: "Does your capital allocation strategy reflect a commitment to sustainability (e.g., green tech investments)?", followUp: "Do you apply an internal carbon price when evaluating new capital expenditures or investments?", weight: 1.3243, sdg: "SDG 9", gri: "GRI 201" },
  { id: "c-economic-resilience", section: "economic", topic: "Resilience", question: "Is your business model resilient to future sustainability challenges and market shifts?", followUp: "Have you conducted climate scenario analysis (e.g., 1.5\u00b0C vs 4\u00b0C) to test your business model?", weight: 1.3243, sdg: "SDG 9, 11", gri: "GRI 2" },
  { id: "c-economic-esg-linked-compensation", section: "economic", topic: "ESG-Linked Compensation", question: "Is senior management compensation linked to the achievement of sustainability performance targets?", followUp: "Is a minimum of 10% of executive variable pay tied to specific, auditable ESG performance metrics?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2-19" },
  { id: "c-economic-financial-inclusion-mobile-money", section: "economic", topic: "Financial Inclusion (Mobile Money)", question: "Do you utilize mobile money or digital fintech platforms to pay unbanked suppliers, casual workers, or rural producers?", followUp: "Does your platform provide these workers with access to further financial services like credit or insurance?", weight: 3.0, sdg: "SDG 1, 9", gri: "GRI 203" },
  { id: "c-economic-common-user-infrastructure", section: "economic", topic: "Common-User Infrastructure", question: "Does the company invest in infrastructure (roads, digital hubs, clinics) that is shared with and accessible to the local public?", followUp: "Do you have a formal maintenance agreement with local authorities to ensure the long-term viability of this shared infrastructure?", weight: 3.0, sdg: "SDG 9, 11", gri: "GRI 203" },
  { id: "c-economic-intra-african-trade-afcfta", section: "economic", topic: "Intra-African Trade (AfCFTA)", question: "Do you have a procurement strategy that prioritizes sourcing materials and services from other African countries (AfCFTA alignment)?", followUp: "Is more than 15% of your cross-border procurement sourced from other African markets?", weight: 1.3243, sdg: "SDG 8, 17", gri: "GRI 201" },
  { id: "c-environmental-energy-climate", section: "environmental", topic: "Energy & Climate", question: "Does your company have initiatives to monitor, reduce, and report on energy consumption and greenhouse gas emissions?", followUp: "Do you have specific science-based targets (SBTs) for these reductions?", weight: 3.0, sdg: "SDG 7, 13", gri: "GRI 302, 305" },
  { id: "c-environmental-waste-circularity", section: "environmental", topic: "Waste & Circularity", question: "Does your company have a formal approach to minimize waste generation and promote circular economy principles?", followUp: "Is at least 50% of your operational waste currently diverted from landfills?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 306" },
  { id: "c-environmental-water-stewardship", section: "environmental", topic: "Water Stewardship", question: "Does your company manage and conserve water resources and assess water-related risks in the supply chain?", followUp: "Do you conduct regular water risk assessments for high-stress geographic areas?", weight: 1.3243, sdg: "SDG 6", gri: "GRI 303" },
  { id: "c-environmental-sustainable-sourcing", section: "environmental", topic: "Sustainable Sourcing", question: "Does your company have systems to verify that raw materials are sustainably or ethically sourced?", followUp: "Are your Tier 1 suppliers required to sign a Sustainable Code of Conduct?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 308" },
  { id: "c-environmental-biodiversity-ecosystems", section: "environmental", topic: "Biodiversity & Ecosystems", question: "Does your company have measures in place to mitigate negative impacts on local biodiversity?", followUp: "Does your company avoid operating in or near protected high-biodiversity areas?", weight: 1.3243, sdg: "SDG 15", gri: "GRI 304" },
  { id: "c-environmental-sustainable-innovation", section: "environmental", topic: "Sustainable Innovation", question: "Does your company develop new products or services with a reduced environmental impact?", followUp: "Is sustainability a formal KPI in your R&D or product development process?", weight: 3.0, sdg: "SDG 9", gri: "GRI 203" },
  { id: "c-environmental-environmental-management-system", section: "environmental", topic: "Environmental Management System", question: "Does your company have a formal environmental management system (e.g., ISO 14001) in place?", followUp: "Is your EMS externally audited or certified (e.g., ISO 14001)?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 307" },
  { id: "c-environmental-supply-chain-footprint", section: "environmental", topic: "Supply Chain Footprint", question: "Does your company assess and manage the environmental footprint of its supply chain?", followUp: "Do you collect primary carbon data from your most significant suppliers?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 308" },
  { id: "c-environmental-reporting-transparency", section: "environmental", topic: "Reporting & Transparency", question: "Does your company publicly report on environmental performance using a recognized framework (e.g., GRI, SASB)?", followUp: "Is your sustainability report prepared in accordance with GRI or SASB standards?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 2" },
  { id: "c-environmental-climate-risk", section: "environmental", topic: "Climate Risk", question: "Does your company assess and respond to climate-related risks and opportunities?", followUp: "Does your reporting align with TCFD recommendations or equivalent standards?", weight: 3.0, sdg: "SDG 13", gri: "GRI 201-2" },
  { id: "c-environmental-energy-access-security", section: "environmental", topic: "Energy Access & Security", question: "Does your company invest in decentralized renewable energy (e.g. mini-grids/solar) to ensure energy security for your operations and neighbors?", followUp: "Do you provide surplus energy generated back to the local grid or community for free or at reduced cost?", weight: 3.0, sdg: "SDG 7", gri: "GRI 203" },
  { id: "c-environmental-water-food-security", section: "environmental", topic: "Water & Food Security", question: "Does the company support local agricultural resilience or shared water resource management in drought-prone areas?", followUp: "Have you funded or implemented water harvesting or irrigation technology for local smallholder farmers?", weight: 3.0, sdg: "SDG 2, 6", gri: "GRI 203" },
  { id: "c-environmental-just-transition", section: "environmental", topic: "Just Transition", question: "Do you have a formal plan to ensure that the shift to green technology does not result in net job losses for the local community?", followUp: "Does your plan include retraining programs for workers affected by the decommissioning of old technologies?", weight: 3.0, sdg: "SDG 7, 8", gri: "GRI 203, 404" },
  { id: "c-social-employee-well-being", section: "social", topic: "Employee Well-being", question: "Does your company have programs or policies to support the physical, mental, and professional well-being of employees?", followUp: "Do you track utilization or impact metrics (e.g., reduction in absenteeism or turnover) for these programs?", weight: 1.3243, sdg: "SDG 3", gri: "GRI 403" },
  { id: "c-social-diversity-equity-inclusion-dei", section: "social", topic: "Diversity, Equity, & Inclusion (DEI)", question: "Does your company actively foster a diverse and inclusive workplace and measure its progress?", followUp: "Do you publicly disclose diversity data (gender/ethnicity) specifically for management and leadership roles?", weight: 1.3243, sdg: "SDG 5, 10", gri: "GRI 405" },
  { id: "c-social-fair-labor-human-rights", section: "social", topic: "Fair Labor & Human Rights", question: "Does your company have systems to ensure fair labor practices and respect for human rights in its operations and supply chain?", followUp: "Do you conduct third-party audits of high-risk suppliers to verify compliance with your policies?", weight: 1.3243, sdg: "SDG 8", gri: "GRI 407, 408, 409" },
  { id: "c-social-community-engagement", section: "social", topic: "Community Engagement", question: "Does your company formally engage with and contribute to the local communities where it operates?", followUp: "Do you track a specific % of pre-tax profit or employee hours dedicated to community impact?", weight: 3.0, sdg: "SDG 11", gri: "GRI 413" },
  { id: "c-social-health-safety", section: "social", topic: "Health & Safety", question: "Does your company have processes for ensuring workplace health and safety and investigating incidents?", followUp: "Is your safety management system externally certified (e.g., ISO 45001)?", weight: 1.3243, sdg: "SDG 3", gri: "GRI 403" },
  { id: "c-social-employee-training-development", section: "social", topic: "Employee Training & Development", question: "Does your company provide opportunities for skill development and training on sustainability topics?", followUp: "Are sustainability KPIs embedded in the annual performance reviews for all employees?", weight: 1.3243, sdg: "SDG 4", gri: "GRI 404" },
  { id: "c-social-data-privacy", section: "social", topic: "Data Privacy", question: "Does your company have policies and controls to ensure the privacy and security of stakeholder data?", followUp: "Is your data protection framework audited against international standards (ISO 27001 or SOC2)?", weight: 1.3243, sdg: "SDG 16", gri: "GRI 418" },
  { id: "c-social-human-capital-reporting", section: "social", topic: "Human Capital Reporting", question: "Does your company publicly report on key human capital metrics like turnover or the gender pay gap?", followUp: "Has your gender pay gap decreased or reached parity over the last three reporting cycles?", weight: 1.3243, sdg: "SDG 8", gri: "GRI 401, 404" },
  { id: "c-social-social-impact", section: "social", topic: "Social Impact", question: "Does your company measure the social impact of its products, services, and philanthropic efforts?", followUp: "Do you use a recognized methodology like SROI (Social Return on Investment) to quantify this impact?", weight: 6.0, sdg: "SDG 1, 10", gri: "GRI 203, 413" },
  { id: "c-social-customer-responsibility", section: "social", topic: "Customer Responsibility", question: "Does your company have policies for product safety, transparent labeling, and responsible marketing?", followUp: "Have there been zero significant product recalls or marketing fines in the last 2 years?", weight: 1.3243, sdg: "SDG 12", gri: "GRI 416, 417" },
  { id: "c-social-informal-sector-integration", section: "social", topic: "Informal Sector Integration", question: "Does your company formally integrate or support informal economy workers (e.g. waste pickers, street vendors) within your supply chain?", followUp: "Do you provide these informal workers with health & safety training or equipment?", weight: 3.0, sdg: "SDG 8, 10", gri: "GRI 203" },
  { id: "c-social-youth-employment-skills", section: "social", topic: "Youth Employment & Skills", question: "Does your company have a dedicated program for youth internships and first-time employment for school/university leavers?", followUp: "Does at least 20% of your new hire intake come from these youth development programs?", weight: 1.3243, sdg: "SDG 4, 8", gri: "GRI 404" },
  { id: "c-social-local-empowerment-procurement", section: "social", topic: "Local Empowerment & Procurement", question: "Do you prioritize procurement from indigenous-owned or local SMEs within the communities where you operate?", followUp: "Is more than 40% of your total procurement spend directed to local or empowerment-verified suppliers?", weight: 3.0, sdg: "SDG 8, 9", gri: "GRI 204" },
  { id: "c-social-ubuntu-led-community-development", section: "social", topic: "Ubuntu-led Community Development", question: "Are your community development projects co-designed with local traditional leadership to ensure long-term communal self-reliance?", followUp: "Do you measure the success of these projects based on communal outcomes rather than just capital spend?", weight: 3.0, sdg: "SDG 11, 17", gri: "GRI 413" },
];

export const STAKEHOLDER_QUESTIONS: Question[] = [
  { id: "s-environmental-energy-management", section: "environmental", topic: "Energy Management", question: "Do you track and report total energy consumption across your operations?", followUp: "Have you set a target to reduce energy consumption by at least 10% in the next 3 years?", weight: 4.0, sdg: "SDG 7", gri: "GRI 302" },
  { id: "s-environmental-ghg-emissions", section: "environmental", topic: "GHG Emissions", question: "Does your company measure its Scope 1 and Scope 2 greenhouse gas emissions?", followUp: "Do you publicly disclose your carbon footprint via platforms like CDP or your annual report?", weight: 4.0, sdg: "SDG 13", gri: "GRI 305" },
  { id: "s-environmental-waste-reduction", section: "environmental", topic: "Waste Reduction", question: "Do you have a waste management program focused on reducing, reusing, and recycling?", followUp: "Is more than 30% of your total waste diverted from landfills or incineration?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 306" },
  { id: "s-environmental-water-stewardship", section: "environmental", topic: "Water Stewardship", question: "Do you monitor water usage and implement conservation measures in your operations?", followUp: "Do you assess the impact of your water discharge on local ecosystems?", weight: 2.1818, sdg: "SDG 6", gri: "GRI 303" },
  { id: "s-environmental-sustainable-packaging", section: "environmental", topic: "Sustainable Packaging", question: "Is at least 50% of your product packaging made from recycled or biodegradable materials?", followUp: "Do you have a take-back program or circularity initiative for your packaging?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 301, 306" },
  { id: "s-environmental-logistics-transport", section: "environmental", topic: "Logistics & Transport", question: "Do you have a policy to minimize the environmental impact of your logistics and transport?", followUp: "Are at least 10% of your fleet vehicles low-emission or electric?", weight: 2.1818, sdg: "SDG 11, 13", gri: "GRI 305" },
  { id: "s-environmental-renewable-energy", section: "environmental", topic: "Renewable Energy", question: "Does your company source a portion of its electricity from renewable sources?", followUp: "Is more than 25% of your total energy consumption powered by renewables?", weight: 2.1818, sdg: "SDG 7", gri: "GRI 302" },
  { id: "s-environmental-ems-certification", section: "environmental", topic: "EMS Certification", question: "Does your company maintain an Environmental Management System (e.g., ISO 14001)?", followUp: "Is your EMS audited annually by an independent third party?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 307" },
  { id: "s-environmental-responsible-sourcing", section: "environmental", topic: "Responsible Sourcing", question: "Do you verify the environmental credentials of your primary raw material suppliers?", followUp: "Do you require suppliers to hold environmental certifications?", weight: 2.1818, sdg: "N/A", gri: "N/A" },
  { id: "s-environmental-product-lifecycle", section: "environmental", topic: "Product Lifecycle", question: "Do you conduct lifecycle assessments (LCAs) for your top-selling products?", followUp: "Have you redesigned a product in the last 2 years specifically to reduce its environmental footprint?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 301" },
  { id: "s-social-fair-labor-practices", section: "social", topic: "Fair Labor Practices", question: "Do you guarantee that all employees are paid a living wage above the legal minimum?", followUp: "Do you conduct regular pay equity audits to ensure no gender pay gaps?", weight: 2.1818, sdg: "SDG 8", gri: "GRI 401, 402" },
  { id: "s-social-health-safety", section: "social", topic: "Health & Safety", question: "Do you have a formal occupational health and safety management system?", followUp: "Is your lost-time injury frequency rate (LTIFR) below the industry average?", weight: 2.1818, sdg: "SDG 3", gri: "GRI 403" },
  { id: "s-social-diversity-inclusion", section: "social", topic: "Diversity & Inclusion", question: "Does your company have a formal Diversity, Equity, and Inclusion (DEI) policy?", followUp: "Is diversity a key metric in your executive performance reviews?", weight: 2.1818, sdg: "SDG 5, 10", gri: "GRI 405" },
  { id: "s-social-modern-slavery", section: "social", topic: "Modern Slavery", question: "Do you have a policy and process to prevent forced labor and human trafficking in your supply chain?", followUp: "Do you perform on-site social audits for high-risk suppliers?", weight: 2.1818, sdg: "SDG 8", gri: "GRI 409" },
  { id: "s-social-employee-training", section: "social", topic: "Employee Training", question: "Do you provide at least 20 hours of training and development per employee annually?", followUp: "Do you offer specific training on sustainability and ethical conduct?", weight: 2.1818, sdg: "SDG 4", gri: "GRI 404" },
  { id: "s-social-freedom-of-association", section: "social", topic: "Freedom of Association", question: "Do you respect the right of employees to join trade unions and bargain collectively?", followUp: "Is there a formal mechanism for employees to provide feedback to management?", weight: 2.1818, sdg: "SDG 8", gri: "GRI 407" },
  { id: "s-social-community-impact", section: "social", topic: "Community Impact", question: "Does your company have a program for community investment or charitable giving?", followUp: "Do you measure the social impact of your community programs?", weight: 4.0, sdg: "SDG 11", gri: "GRI 413" },
  { id: "s-social-data-privacy", section: "social", topic: "Data Privacy", question: "Do you have robust policies to protect the personal data of customers and employees?", followUp: "Have you avoided any major data breaches or privacy violations in the last 12 months?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 418" },
  { id: "s-social-employee-wellbeing", section: "social", topic: "Employee Wellbeing", question: "Do you offer mental health support and flexible working arrangements for employees?", followUp: "Do you conduct annual employee engagement surveys with follow-up action plans?", weight: 2.1818, sdg: "SDG 3", gri: "GRI 403" },
  { id: "s-social-human-rights", section: "social", topic: "Human Rights", question: "Do you have a public commitment to respect human rights as per UN Guiding Principles?", followUp: "Is there a grievance mechanism accessible to all stakeholders to report human rights concerns?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 412" },
  { id: "s-governance-ethical-conduct", section: "governance", topic: "Ethical Conduct", question: "Does your company have a written Code of Ethics and Anti-Bribery policy?", followUp: "Is mandatory ethics training provided to all employees annually?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 205, 206" },
  { id: "s-governance-esg-oversight", section: "governance", topic: "ESG Oversight", question: "Does your Board of Directors have direct oversight of sustainability/ESG risks?", followUp: "Is there a dedicated ESG committee at the board or executive level?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2-12" },
  { id: "s-governance-reporting-transparency", section: "governance", topic: "Reporting Transparency", question: "Do you produce an annual sustainability report following international standards (e.g., GRI, SASB)?", followUp: "Is your sustainability report verified by an independent third party?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2" },
  { id: "s-governance-supply-chain-governance", section: "governance", topic: "Supply Chain Governance", question: "Do you require all tier-1 suppliers to sign a Supplier Code of Conduct?", followUp: "Do you terminate contracts with suppliers who fail to meet ethical standards?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 308, 414" },
  { id: "s-governance-stakeholder-engagement", section: "governance", topic: "Stakeholder Engagement", question: "Do you have a formal process for identifying and engaging with key stakeholders?", followUp: "Do you conduct a formal materiality assessment at least every two years?", weight: 2.1818, sdg: "SDG 17", gri: "GRI 2-29" },
  { id: "s-governance-executive-compensation", section: "governance", topic: "Executive Compensation", question: "Is a portion of executive compensation tied to the achievement of ESG targets?", followUp: "Are these targets clearly disclosed in your annual report?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2-19" },
  { id: "s-governance-whistleblower-protection", section: "governance", topic: "Whistleblower Protection", question: "Do you have a confidential whistleblowing hotline that is strictly enforced?", followUp: "Do you have a zero-tolerance policy for retaliation against whistleblowers?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2-25, 2-26" },
  { id: "s-governance-risk-management", section: "governance", topic: "Risk Management", question: "Are ESG risks integrated into your enterprise risk management (ERM) framework?", followUp: "Do you perform climate-related scenario analysis (e.g., TCFD recommendations)?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2" },
  { id: "s-governance-political-engagement", section: "governance", topic: "Political Engagement", question: "Do you disclose all political contributions and lobbying activities?", followUp: "Is your lobbying activity aligned with the Paris Agreement on climate change?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 415" },
  { id: "s-governance-compliance-audits", section: "governance", topic: "Compliance Audits", question: "Do you conduct regular internal and external audits for regulatory compliance?", followUp: "Have you remained free of significant fines or legal actions in the last 2 years?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 2-27" },
  { id: "s-economic-financial-stability", section: "economic", topic: "Financial Stability", question: "Has your company remained profitable or financially stable over the last 3 fiscal years?", followUp: "Do you maintain a healthy debt-to-equity ratio compared to industry peers?", weight: 2.1818, sdg: "SDG 8", gri: "GRI 201" },
  { id: "s-economic-local-economic-impact", section: "economic", topic: "Local Economic Impact", question: "Do you prioritize local suppliers for your procurement needs (e.g., within the same region)?", followUp: "Is more than 30% of your procurement spend directed toward local or small-scale enterprises?", weight: 4.0, sdg: "SDG 8", gri: "GRI 201, 202, 203" },
  { id: "s-economic-r-d-innovation", section: "economic", topic: "R&D & Innovation", question: "Do you invest at least 2% of annual revenue into Research and Development?", followUp: "Is more than 20% of your R&D budget dedicated to sustainable innovation?", weight: 4.0, sdg: "SDG 9", gri: "GRI 203" },
  { id: "s-economic-supply-chain-resilience", section: "economic", topic: "Supply Chain Resilience", question: "Do you have a business continuity plan that addresses supply chain disruptions?", followUp: "Do you multi-source critical components to reduce dependency on single suppliers?", weight: 2.1818, sdg: "SDG 9", gri: "GRI 2" },
  { id: "s-economic-tax-transparency", section: "economic", topic: "Tax Transparency", question: "Do you publish a tax strategy and disclose taxes paid on a country-by-country basis?", followUp: "Do you avoid the use of tax havens for the purpose of tax evasion?", weight: 4.0, sdg: "SDG 16, 17", gri: "GRI 207" },
  { id: "s-economic-fair-competition", section: "economic", topic: "Fair Competition", question: "Do you have a formal policy promoting fair competition and anti-trust compliance?", followUp: "Do you provide anti-trust training to your sales and procurement teams?", weight: 2.1818, sdg: "SDG 16", gri: "GRI 206" },
  { id: "s-economic-infrastructure-investment", section: "economic", topic: "Infrastructure Investment", question: "Do you invest in local infrastructure or public services where you operate?", followUp: "Do your investments support long-term sustainable development goals in the region?", weight: 4.0, sdg: "SDG 9", gri: "GRI 203" },
  { id: "s-economic-market-growth", section: "economic", topic: "Market Growth", question: "Has your market share or revenue grown consistently over the last 3 years?", followUp: "Is this growth driven by sustainable or ethical product lines?", weight: 2.1818, sdg: "SDG 8", gri: "GRI 201" },
  { id: "s-economic-resource-efficiency", section: "economic", topic: "Resource Efficiency", question: "Have you achieved cost savings through resource efficiency (e.g., energy/water/waste) in the last year?", followUp: "Are these savings reinvested into further sustainability initiatives?", weight: 2.1818, sdg: "SDG 12", gri: "GRI 301, 302, 303" },
  { id: "s-economic-long-term-strategy", section: "economic", topic: "Long-term Strategy", question: "Is sustainability central to your long-term business strategy and value creation plan?", followUp: "Do you report on the long-term economic value generated for all stakeholders, not just shareholders?", weight: 2.1818, sdg: "SDG 8, 9", gri: "GRI 2" },
];

export function questionsFor(audience: "client" | "stakeholder"): Question[] {
  const bank = audience === "client" ? CLIENT_QUESTIONS : STAKEHOLDER_QUESTIONS;
  return SECTION_ORDER.flatMap((section) =>
    bank.filter((q) => q.section === section),
  );
}

export function sectionById(id: SectionId): Section {
  return SECTIONS.find((s) => s.id === id)!;
}
